### PR TITLE
Refactor my jobs

### PR DESCRIPTION
**Pull request by bmrsny**
Removed reference to my jobs from jobs controller and added it to it's own MyJobs controller.

### CODE REVIEW

**Comment by EmilyMB** [comment]
I thought that Steve's recommendation was to have My jobs be the default for the jobs_path with the JobController having:
`def index; @jobs = current_user.jobs; end`

From there, we could have the AllJobsController (and maybe a Relevant Jobs controller? Or maybe just a scope?).

**Comment by bmrsny** [comment]
My thought is that when I get on the site, I initially want to browse through all the jobs and find some more jobs to add to my jobs. Maybe we could get some more input on this?

**Comment by EmilyMB** [comment]
@bmrsny: yeah, I guess that makes sense, and it looks like @mikedao likes it so let's go with it.

**Comment by EmilyMB** [comment]
OK. I'm working on refactoring this.

**Comment by larsonkonr** [comment]
Looks good sir

**Comment by EmilyMB** [comment]
I was still working on this!

**Pull request merged**
